### ISSUE TITLE
YM3812 VGM recording is not accurate

### ISSUE THREAD

**Issue by denjhang** [110-kenichi/mame#10]
0,0,8,3,11,15,,14,3,1,1,1,0,0,1,15,2,9,15,,0,0,1,1,1,0,0,0

I tried the above OPL2 Timber and found that there is a big gap between the recorded WAV and VGM. I use the latest version of in_VGM (0.50.0) to play VGM.

**Comment by denjhang** [comment]
[YM3812 piano.zip](https://github.com/110-kenichi/mame/files/7745257/YM3812.piano.zip)

**Comment by 110-kenichi** [comment]
I've fixed.
https://github.com/110-kenichi/mame/releases/tag/v4.1.0.3

**Comment by denjhang** [comment]
It seems that the problem is still not resolved. This is my latest recorded vgm.Here I obviously set the WS of operator1 to 1, but it sounds similar to the result of 0.
`0,6,12,2,4,15,,40,0,1,1,1,0,1,1,10,2,7,15,,0,0,1,1,0,0,1,0`
[YM3812_0_2022-3-30_10-35-04_0.zip](https://github.com/110-kenichi/mame/files/8376575/YM3812_0_2022-3-30_10-35-04_0.zip)

**Comment by denjhang** [comment]
https://github.com/110-kenichi/mame/releases/download/v4.1.0.3/MAmidiMEmo_x86.zip

I understand, the program of this link is actually still 4.1.0.2.

**Comment by denjhang** [comment]
![截图未命名0330105352](https://user-images.githubusercontent.com/61811583/160741677-33f893f0-6a3c-4506-87fe-2e7cb646c68d.jpeg)

**Comment by denjhang** [comment]
So, v4.1.0.3 fixes the problem, but the v4.1.0.3 x86 precompiled file link points to a v4.1.0.2 version. Actually only the precompiled files for v4.1.0.3 x64 link correctly.

**Comment by 110-kenichi** [comment]
Oops, so sorry.
I've re-uploaded. Could you please confirm this?
https://github.com/110-kenichi/mame/releases/tag/v4.1.0.3

**Comment by denjhang** [comment]
ok
